ifeq ($(shell uname),Darwin)
LIB = -DMAC -framework OpenGL -framework GLUT
else
LIB = -lGL -lGLU -lglut
endif

LIB2 = libim/libim.a jpeg/libjpeg.a
CC = g++ -std=c++11 -Wall -Wno-deprecated-declarations -O3

project: proj4.cpp $(LIB2)
	$(CC) -o proj4 proj4.cpp $(LIB) $(LIB2)

jpeg/libjpeg.a:
	cd jpeg; make; cd ..

libim/libim.a:
	cd libim; make; cd ..